/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.khachHangController;
import controller.vanChuyenController;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import model.Users;
import model.XeVanChuyen;

/**
 *
 * @author Dell
 */
public class QLDuLieu extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyDonHang
     */
    private static Users user_logged;
    private khachHangController kh_controller;
    private vanChuyenController pt_controller;

    public QLDuLieu(Users user_logged) {
        initComponents();
        setLocationRelativeTo(null);
        this.user_logged = user_logged;
        kh_controller = new khachHangController();
        pt_controller = new vanChuyenController();
        loadData_KH();
        loadData_PT();
        lbUsername.setText(user_logged.getUsername());
    }

    void kh_ClearTxt() {
        txtID_KH.setText("");
        txtTen_KH.setText("");
        txt_SDT_KH.setText("");
        txtDiaChi_KH.setText("");
        txt_KH_Tim.setText("");
    }

    void pt_Clear() {
        txt_PT_Tim.setText("");
        txt_PT_ID.setText("");
        txt_PT_TaiXe.setText("");
        txt_PT_BienSo.setText("");
        txt_PT_LoaiXe.setText("");
    }

    void loadData_KH() {
        DefaultTableModel tableModel = new DefaultTableModel(new String[]{"ID", "Tên Khách hàng", "Số điện thoại", "Địa chỉ"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (KhachHang kh : kh_controller.getdsKhachHang()) {
            tableModel.addRow(new Object[]{kh.getMaKhachHang(), kh.getTenKhachHang(), kh.getSdt(), kh.getDiachi()});
        }
        kh_table.setModel(tableModel);
    }

    void loadData_KH(List<KhachHang> dskh) {
        DefaultTableModel tableModel = new DefaultTableModel(new String[]{"ID", "Tên Khách hàng", "Số điện thoại", "Địa chỉ"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (KhachHang kh : dskh) {
            tableModel.addRow(new Object[]{kh.getMaKhachHang(), kh.getTenKhachHang(), kh.getSdt(), kh.getDiachi()});
        }
        kh_table.setModel(tableModel);
    }

    void loadData_PT() {
        DefaultTableModel tableModel = new DefaultTableModel(new String[]{"ID", "Biển Số", "Tài Xế", "Loại Xe"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (XeVanChuyen xe : pt_controller.getdsPhuongTien()) {
            tableModel.addRow(new Object[]{xe.getMaXe(), xe.getBienSo(), xe.getTaiXe(), xe.getLoaiXe()});
        }
        pt_table.setModel(tableModel);
    }

    void loadData_PT(List<XeVanChuyen> ds) {
        DefaultTableModel tableModel = new DefaultTableModel(new String[]{"ID", "Biển Số", "Tài Xế", "Loại Xe"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (XeVanChuyen xe : ds) {
            tableModel.addRow(new Object[]{xe.getMaXe(), xe.getBienSo(), xe.getTaiXe(), xe.getLoaiXe()});
        }
        pt_table.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelKhachHang = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnDangXuat2 = new javax.swing.JButton();
        btnCTDonHang2 = new javax.swing.JButton();
        btnQLDonHang3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        btnQLDonHang1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kh_table = new javax.swing.JTable();
        txtID_KH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTen_KH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_SDT_KH = new javax.swing.JTextField();
        lbDiaChi = new javax.swing.JLabel();
        txtDiaChi_KH = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn_KH_Them = new javax.swing.JButton();
        btn_KH_Xoa = new javax.swing.JButton();
        btn_KH_Sua = new javax.swing.JButton();
        btn_KH_Tim = new javax.swing.JButton();
        txt_KH_Tim = new javax.swing.JTextField();
        panelPhuongTien = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pt_table = new javax.swing.JTable();
        txt_PT_ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_PT_BienSo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_PT_TaiXe = new javax.swing.JTextField();
        lbDiaChi1 = new javax.swing.JLabel();
        txt_PT_LoaiXe = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btn_PT_Them = new javax.swing.JButton();
        btn_PT_Xoa = new javax.swing.JButton();
        btn_PT_Sua = new javax.swing.JButton();
        btn_PT_Tim = new javax.swing.JButton();
        txt_PT_Tim = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 92, 103));

        btnDangXuat2.setBackground(java.awt.Color.orange);
        btnDangXuat2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangXuat2.setText("Đăng xuất");
        btnDangXuat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnCTDonHang2.setBackground(new java.awt.Color(255, 153, 51));
        btnCTDonHang2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCTDonHang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bill.png"))); // NOI18N
        btnCTDonHang2.setText("Quản lý dữ liệu");
        btnCTDonHang2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCTDonHang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTDonHangActionPerformed(evt);
            }
        });

        btnQLDonHang3.setBackground(java.awt.Color.orange);
        btnQLDonHang3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQLDonHang3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box.png"))); // NOI18N
        btnQLDonHang3.setText("Quản lý đơn hàng");
        btnQLDonHang3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQLDonHang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDonHangActionPerformed(evt);
            }
        });

        jPanel7.setBackground(java.awt.Color.orange);
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Xin chào, ");

        lbUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUsername.setForeground(new java.awt.Color(255, 0, 0));
        lbUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsername.setText("UserName");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(lbUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnQLDonHang1.setBackground(java.awt.Color.orange);
        btnQLDonHang1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQLDonHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.png"))); // NOI18N
        btnQLDonHang1.setText("Trang chủ");
        btnQLDonHang1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQLDonHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDonHang1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnDangXuat2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCTDonHang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLDonHang3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLDonHang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnQLDonHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnQLDonHang3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnCTDonHang2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnDangXuat2)
                .addGap(31, 31, 31))
        );

        jPanel9.setBackground(new java.awt.Color(224, 224, 224));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 92, 103));
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        kh_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        kh_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        kh_table.setShowGrid(true);
        kh_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kh_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kh_table);

        txtID_KH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID_KH.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Họ và tên:");

        txtTen_KH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("SĐT:");

        txt_SDT_KH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDiaChi.setText("Địa chỉ:");

        txtDiaChi_KH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(lbDiaChi)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiaChi_KH, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SDT_KH, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID_KH, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen_KH, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID_KH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTen_KH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_SDT_KH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChi_KH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDiaChi))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel4.setBackground(new java.awt.Color(0, 92, 103));

        btn_KH_Them.setBackground(java.awt.Color.orange);
        btn_KH_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_KH_Them.setText("Thêm");
        btn_KH_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KH_ThemActionPerformed(evt);
            }
        });

        btn_KH_Xoa.setBackground(java.awt.Color.orange);
        btn_KH_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_KH_Xoa.setText("Xóa");
        btn_KH_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KH_XoaActionPerformed(evt);
            }
        });

        btn_KH_Sua.setBackground(java.awt.Color.orange);
        btn_KH_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_KH_Sua.setText("Sửa");
        btn_KH_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KH_SuaActionPerformed(evt);
            }
        });

        btn_KH_Tim.setBackground(java.awt.Color.orange);
        btn_KH_Tim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_KH_Tim.setText("Tìm kiếm");
        btn_KH_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KH_TimActionPerformed(evt);
            }
        });

        txt_KH_Tim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btn_KH_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_KH_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_KH_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_KH_Tim)
                .addGap(46, 46, 46)
                .addComponent(txt_KH_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_KH_Them)
                    .addComponent(btn_KH_Xoa)
                    .addComponent(btn_KH_Sua)
                    .addComponent(btn_KH_Tim)
                    .addComponent(txt_KH_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelKhachHangLayout = new javax.swing.GroupLayout(panelKhachHang);
        panelKhachHang.setLayout(panelKhachHangLayout);
        panelKhachHangLayout.setHorizontalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKhachHangLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelKhachHangLayout.setVerticalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelKhachHangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Khách Hàng", panelKhachHang);

        jPanel10.setBackground(new java.awt.Color(224, 224, 224));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 92, 103));
        jLabel4.setText("QUẢN LÝ PHƯƠNG TIỆN");

        pt_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pt_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pt_table.setShowGrid(true);
        pt_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pt_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pt_table);

        txt_PT_ID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_PT_ID.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Biển số:");

        txt_PT_BienSo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tài xế:");

        txt_PT_TaiXe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbDiaChi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDiaChi1.setText("Loại xe:");

        txt_PT_LoaiXe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(lbDiaChi1)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_PT_LoaiXe)
                    .addComponent(txt_PT_TaiXe)
                    .addComponent(txt_PT_BienSo)
                    .addComponent(txt_PT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_PT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_PT_BienSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_PT_TaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_PT_LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDiaChi1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel8.setBackground(new java.awt.Color(0, 92, 103));

        btn_PT_Them.setBackground(java.awt.Color.orange);
        btn_PT_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_PT_Them.setText("Thêm");
        btn_PT_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PT_ThemActionPerformed(evt);
            }
        });

        btn_PT_Xoa.setBackground(java.awt.Color.orange);
        btn_PT_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_PT_Xoa.setText("Xóa");
        btn_PT_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PT_XoaActionPerformed(evt);
            }
        });

        btn_PT_Sua.setBackground(java.awt.Color.orange);
        btn_PT_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_PT_Sua.setText("Sửa");
        btn_PT_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PT_SuaActionPerformed(evt);
            }
        });

        btn_PT_Tim.setBackground(java.awt.Color.orange);
        btn_PT_Tim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_PT_Tim.setText("Tìm kiếm");
        btn_PT_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PT_TimActionPerformed(evt);
            }
        });

        txt_PT_Tim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_PT_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn_PT_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_PT_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btn_PT_Tim)
                .addGap(45, 45, 45)
                .addComponent(txt_PT_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_PT_Them)
                    .addComponent(btn_PT_Xoa)
                    .addComponent(btn_PT_Sua)
                    .addComponent(btn_PT_Tim)
                    .addComponent(txt_PT_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPhuongTienLayout = new javax.swing.GroupLayout(panelPhuongTien);
        panelPhuongTien.setLayout(panelPhuongTienLayout);
        panelPhuongTienLayout.setHorizontalGroup(
            panelPhuongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPhuongTienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPhuongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPhuongTienLayout.setVerticalGroup(
            panelPhuongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPhuongTienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Phương tiện", panelPhuongTien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLDonHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDonHang1ActionPerformed
        // TODO add your handling code here:
        new MainBoard(user_logged).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLDonHang1ActionPerformed

    private void btnQLDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDonHangActionPerformed
        // TODO add your handling code here:
        new QLDonHang(user_logged).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLDonHangActionPerformed

    private void btnCTDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTDonHangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCTDonHangActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        int confirmation = JOptionPane.showConfirmDialog(
                null,
                "Bạn có chắc chắn muốn đăng xuất??",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION
        );
        if (confirmation == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btn_KH_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KH_ThemActionPerformed
        try {
            // TODO add your handling code here:
            if (txtTen_KH.getText().isEmpty() || txt_SDT_KH.getText().isEmpty() || txtDiaChi_KH.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin khách hàng!!");
                return;
            }
            String name = txtTen_KH.getText();
            String sdt = txt_SDT_KH.getText();
            String diachi = txtDiaChi_KH.getText();
            if (kh_controller.add_khachhang(name, sdt, diachi) != 0) {
                JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!!");
                loadData_KH();
                kh_ClearTxt();
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi ~~");
            }
        } catch (SQLException ex) {
            Logger.getLogger(QLDuLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_KH_ThemActionPerformed

    private void kh_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kh_tableMouseClicked
        // TODO add your handling code here:
        int selectedRow = kh_table.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) kh_table.getModel();
            txtID_KH.setText(model.getValueAt(selectedRow, 0).toString());
            txtTen_KH.setText(model.getValueAt(selectedRow, 1).toString());
            txt_SDT_KH.setText(model.getValueAt(selectedRow, 2).toString());
            txtDiaChi_KH.setText(model.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_kh_tableMouseClicked

    private void btn_KH_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KH_XoaActionPerformed
        // TODO add your handling code here:
        if (txtID_KH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng!!");
            return;
        }
        int id = Integer.parseInt(txtID_KH.getText());
        int confirmation = JOptionPane.showConfirmDialog(
                null,
                "Bạn có chắc chắn muốn xóa khách hàng có ID: " + txtID_KH.getText() + "?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
        );
        if (confirmation == JOptionPane.YES_OPTION) {
            if (kh_controller.remove_khachhang(id)) {
                JOptionPane.showMessageDialog(this, "Xóa sản phẩm có ID: " + txtID_KH.getText() + " thành công");
                kh_ClearTxt();
                loadData_KH();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi ~~");
        }

    }//GEN-LAST:event_btn_KH_XoaActionPerformed

    private void btn_KH_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KH_SuaActionPerformed
        // TODO add your handling code here:
        if (txtID_KH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng!!");
            return;
        }
        if (txtTen_KH.getText().isEmpty() || txt_SDT_KH.getText().isEmpty() || txtDiaChi_KH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin khách hàng!!");
            return;
        }
        int id = Integer.parseInt(txtID_KH.getText());
        String name = txtTen_KH.getText();
        String sdt = txt_SDT_KH.getText();
        String diachi = txtDiaChi_KH.getText();
        int confirmation = JOptionPane.showConfirmDialog(
                null,
                "Bạn có chắc chắn muốn chỉnh sửa khách hàng có ID: " + txtID_KH.getText() + "?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION
        );
        if (confirmation == JOptionPane.YES_OPTION) {
            try {
                if (kh_controller.edit_khachhang(new KhachHang(id, name, sdt, diachi))) {
                    JOptionPane.showMessageDialog(this, "Sửa khách hàng có ID: " + txtID_KH.getText() + " thành công");
                    kh_ClearTxt();
                    loadData_KH();
                }
            } catch (SQLException ex) {
                Logger.getLogger(QLDuLieu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_KH_SuaActionPerformed

    private void btn_KH_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KH_TimActionPerformed
        // TODO add your handling code here:
        if (txt_KH_Tim.getText().isEmpty()) {
            loadData_KH();
        } else {
            loadData_KH(kh_controller.getdsKhachHang(txt_KH_Tim.getText()));
        }

    }//GEN-LAST:event_btn_KH_TimActionPerformed

    private void pt_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pt_tableMouseClicked
        // TODO add your handling code here:
        int selectedRow = pt_table.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) pt_table.getModel();
            txt_PT_ID.setText(model.getValueAt(selectedRow, 0).toString());
            txt_PT_BienSo.setText(model.getValueAt(selectedRow, 1).toString());
            txt_PT_TaiXe.setText(model.getValueAt(selectedRow, 2).toString());
            txt_PT_LoaiXe.setText(model.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_pt_tableMouseClicked

    private void btn_PT_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PT_ThemActionPerformed
        // TODO add your handling code here:
        if (txt_PT_BienSo.getText().isEmpty() || txt_PT_TaiXe.getText().isEmpty() || txt_PT_LoaiXe.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            return;
        }
        String bienso = txt_PT_BienSo.getText();
        String taixe = txt_PT_TaiXe.getText();
        String loaixe = txt_PT_LoaiXe.getText();
        try {
            if (pt_controller.add_vanchuyen(bienso, taixe, loaixe)) {
                JOptionPane.showMessageDialog(this, "Thêm phương tiện thành công!!!");
                pt_Clear();
                loadData_PT();
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra~~");
            }
        } catch (SQLException ex) {
            Logger.getLogger(QLDuLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_PT_ThemActionPerformed

    private void btn_PT_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PT_XoaActionPerformed
        // TODO add your handling code here:
        if (txt_PT_ID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phương tiện!!");
            return;
        }
        int id = Integer.parseInt(txt_PT_ID.getText());
        int confirmation = JOptionPane.showConfirmDialog(
                null,
                "Bạn có chắc chắn muốn xóa phương tiện có ID: " + txtID_KH.getText() + "?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
        );
        if (confirmation == JOptionPane.YES_OPTION) {
            if (pt_controller.remove_vanchuyen(id)) {
                JOptionPane.showMessageDialog(this, "Xóa phương tiện có ID: " + txtID_KH.getText() + " thành công");
                pt_Clear();
                loadData_PT();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi ~~");
        }
    }//GEN-LAST:event_btn_PT_XoaActionPerformed

    private void btn_PT_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PT_SuaActionPerformed
        // TODO add your handling code here:
        if (txt_PT_ID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phương tiện!!");
            return;
        }
        if (txt_PT_BienSo.getText().isEmpty() || txt_PT_TaiXe.getText().isEmpty() || txt_PT_LoaiXe.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin phương tiện!!");
            return;
        }
        int id = Integer.parseInt(txt_PT_ID.getText());
        String bienso = txt_PT_BienSo.getText();
        String taixe = txt_PT_TaiXe.getText();
        String loaixe = txt_PT_LoaiXe.getText();
        int confirmation = JOptionPane.showConfirmDialog(
                null,
                "Bạn có chắc chắn muốn chỉnh sửa phương tiện có ID: " + txt_PT_ID.getText() + "?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION
        );
        if (confirmation == JOptionPane.YES_OPTION) {
            try {
                if (pt_controller.edit_vanchuyen(new XeVanChuyen(id, bienso, taixe, loaixe))) {
                    JOptionPane.showMessageDialog(this, "Sửa phương tiện thành công có ID: " + txt_PT_ID.getText() + " thành công");
                    pt_Clear();
                    loadData_PT();
                }
            } catch (SQLException ex) {
                Logger.getLogger(QLDuLieu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_PT_SuaActionPerformed

    private void btn_PT_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PT_TimActionPerformed
        // TODO add your handling code here:
        if (txt_PT_Tim.getText().isEmpty()) {
            loadData_PT();
        } else {
            loadData_PT(pt_controller.getdsPhuongTien(txt_PT_Tim.getText()));
        }
    }//GEN-LAST:event_btn_PT_TimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDuLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDuLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDuLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDuLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDuLieu(user_logged).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCTDonHang2;
    private javax.swing.JButton btnDangXuat2;
    private javax.swing.JButton btnQLDonHang1;
    private javax.swing.JButton btnQLDonHang3;
    private javax.swing.JButton btn_KH_Sua;
    private javax.swing.JButton btn_KH_Them;
    private javax.swing.JButton btn_KH_Tim;
    private javax.swing.JButton btn_KH_Xoa;
    private javax.swing.JButton btn_PT_Sua;
    private javax.swing.JButton btn_PT_Them;
    private javax.swing.JButton btn_PT_Tim;
    private javax.swing.JButton btn_PT_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable kh_table;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbDiaChi1;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPanel panelKhachHang;
    private javax.swing.JPanel panelPhuongTien;
    private javax.swing.JTable pt_table;
    private javax.swing.JTextField txtDiaChi_KH;
    private javax.swing.JTextField txtID_KH;
    private javax.swing.JTextField txtTen_KH;
    private javax.swing.JTextField txt_KH_Tim;
    private javax.swing.JTextField txt_PT_BienSo;
    private javax.swing.JTextField txt_PT_ID;
    private javax.swing.JTextField txt_PT_LoaiXe;
    private javax.swing.JTextField txt_PT_TaiXe;
    private javax.swing.JTextField txt_PT_Tim;
    private javax.swing.JTextField txt_SDT_KH;
    // End of variables declaration//GEN-END:variables
}
